### ISSUE TITLE
NameError: name 'OrderedYaml' is not defined

### ISSUE THREAD

**Issue by ZzzTD** [Algolzw/image-restoration-sde#14]
May I ask if anyone has encountered this problem?
Traceback (most recent call last):
  File "E:\Pythonfiles\image-restoration-sde-main\codes\config\deraining\train.py", line 16, in <module>
    import config.deraining.options as option
  File "E:\Pythonfiles\image-restoration-sde-main\codes\config\deraining\options.py", line 15, in <module>
    Loader, Dumper = OrderedYaml()
NameError: name 'OrderedYaml' is not defined

**Comment by Algolzw** [comment]
Hi, you may need to adjustment the line 10 and 11 in options.py to make it work on windows. As suggested here: https://github.com/Algolzw/image-restoration-sde/issues/6#issuecomment-1529268012
