### ISSUE TITLE
app.py

### ISSUE THREAD

**Issue by WangSheng612** [Algolzw/image-restoration-sde#20]
When I Run app.py There are these erros. Thank you 

Traceback (most recent call last):
  File "E:\image-restoration-sde-main\image-restoration-sde-main\codes\config\deraining\app.py", line 16, in <module>
    opt = option.parse(parser.parse_args().opt, is_train=False)
  File "E:\image-restoration-sde-main\image-restoration-sde-main\codes\config\deraining\options.py", line 67, in parse
    config_dir = path.split("/")[-2]
IndexError: list index out of range

**Comment by Algolzw** [comment]
Hi! If you are using the Windows system you should modify the 'options.py' to change the path to Windows format (line 67).
To simply debug it, you can also print the path to find the truth split symbol.

Best.

**Comment by WangSheng612** [comment]
Thank you，I have solved this problem by your advice^^
