### ISSUE TITLE
Dataset for reproducing Gaussian image de-noising model in IR-SDE paper

### ISSUE THREAD

**Issue by shengyenlin** [Algolzw/image-restoration-sde#28]
Hi, 

Thanks for your amazing work.

I was wondering where could I download the dataset for the Gaussian image de-noising model.

Referring to the "To evaluate the image denoising performance, we train our models on 8 294 high-quality images collected from the DIV2K (Agustsson & Timofte, 2017), Flickr2K (Timofte et al., 2017), BSD500 (Arbelaez et al., 2010), and Waterloo Exploration datasets (Ma et al., 2016)." here in your IR-SDE paper.

Thanks in advance.

**Comment by Algolzw** [comment]
Hej, thanks for your interest in our work. The denoising datasets (both training and testing) can be downloaded from the [SwinIR](https://github.com/JingyunLiang/SwinIR#training).

Best.

**Comment by shengyenlin** [comment]
Hi,

I have some problems while training a customized dataset on this model and would appreciate your help on this matter.

I would like to ask if I want to train this model on gray scale image denoising, but I have colorful images. Which part of the config file (i.e. .yml file) should I modify?

Should I change the "color" argument in the "dataset" to gray, and also the "in_nc" and "out_nc" in "network_G"?

I meet some problems when changing the above parameters. I have 4 A100 GPUs (memory = 43GB) and I tried to use distributed training here.

If I set batch size = 8 or above (# of data = 2 for each GPU), I always have OOM problem. But if I change to 4 (i.e. 1 per GPU), I get the following error:

Traceback (most recent call last):
  File "/p/project/delia-mp/lin4/image-restoration-sde/codes/config/denoising-sde/train.py", line 399, in <module>
    main()
  File "/p/project/delia-mp/lin4/image-restoration-sde/codes/config/denoising-sde/train.py", line 321, in main
    model.optimize_parameters(current_step, timesteps, sde)
  File "/p/project/delia-mp/lin4/image-restoration-sde/codes/config/denoising-sde/models/denoising_model.py", line 149, in optimize_parameters
    noise = self.model(self.LQ, timesteps.squeeze())
  File "/p/project/delia-mp/lin4/venv/miniconda3/envs/ir-sde/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/p/project/delia-mp/lin4/venv/miniconda3/envs/ir-sde/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/p/project/delia-mp/lin4/venv/miniconda3/envs/ir-sde/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/p/project/delia-mp/lin4/venv/miniconda3/envs/ir-sde/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/p/project/delia-mp/lin4/image-restoration-sde/codes/config/denoising-sde/models/modules/DenoisingUNet_arch.py", line 95, in forward
    t = self.time_mlp(time)
  File "/p/project/delia-mp/lin4/venv/miniconda3/envs/ir-sde/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/p/project/delia-mp/lin4/venv/miniconda3/envs/ir-sde/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/p/project/delia-mp/lin4/venv/miniconda3/envs/ir-sde/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/p/project/delia-mp/lin4/image-restoration-sde/codes/config/denoising-sde/models/modules/module_util.py", line 39, in forward
    emb = x[:, None] * emb[None, :]
IndexError: too many indices for tensor of dimension 0

**Comment by Algolzw** [comment]
Yes, you need to change the `color` to 'gray', and set `in_nc` and `out_nc` to 1.

For the OOM problem, can you provide your `option.yml` file?

**Comment by shengyenlin** [comment]
Hi, 

Thanks for your prompt response, my `option.yml` is the following

`#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
gpu_ids: [0,1,2,3]

sde:
  max_sigma: 70  # 0.5, TODO: what is this
  T: 1000
  schedule: cosine # cosine # linear

degradation:
  sigma: 50
  noise_type: G # Gaussian noise: G
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: GT
    dataroot_GT: /p/scratch/delia-mp/lin4/restormer_dataset/train/DFWB

    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 4 # need to be a multiple of "number of gpus"
    GT_size: 128 # training patch size
    use_flip: true
    use_rot: true
    color: Gray # originally, RGB
  val:
    name: Test_Dataset
    mode: GT
    dataroot_GT: /p/scratch/delia-mp/lin4/restormer_dataset/test/BSD68

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1 # 3, for colorful image
    out_nc: 1 # 3, for colorful image
    nf: 64
    depth: 4

#### path
path:
  #TODO: change to the state you want
  pretrain_model_G: ~ # /p/project/delia-mp/lin4/image-restoration-sde/codes/config/denoising-sde/log/ir-sde/models/latest_G.pth
  strict_load: true
  resume_state: /p/project/delia-mp/lin4/image-restoration-sde/codes/config/denoising-sde/log/ir-sde/training_state/2000.state
   

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 700000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-6

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 2000

#### logger
logger:
  print_freq: 200
  # save_checkpoint_freq: !!float 1e4
  save_checkpoint_freq: 10000`

**Comment by Algolzw** [comment]
It seems correct. But can you use one GPU? I just tried that I can train this model even on a TITAN XP (12G) with batch size 8. And for multi-GPU training you may need to change the training command (in `demo.sh`) to:

`python -m torch.distributed.launch --nproc_per_node=4 --master_port=1234 train.py -opt=options/train/ir-sde.yml --launcher pytorch`

**Comment by shengyenlin** [comment]
Hi,

I'm really grateful for your prompt response, let me explain my situation in a more detailed way.

I was trying to train the model with torch.distributed.launch", but when I use the command that you provided, it seems that different process on the nodes seem to not communicate with each other (Error message: The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use)). But some times even if this error appears, the training process is still continuing.
 
After some research, I tried to use torch.distributed.run(which is recommended by the official PyTorch now), but I found that the code didn't fully utilize GPU memory on each GPU of a node. (The allocated memory + reversed memory + free memory is not equal to the total capacity).

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.15 GiB (GPU 0; 39.39 GiB total capacity; 4.64 GiB already allocated; 744.56 MiB free; 4.67 GiB reserved in total by PyTorch)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 870.00 MiB (GPU 1; 39.39 GiB total capacity; 5.37 GiB already allocated; 4.73 GiB free; 6.13 GiB reserved in total by PyTorch)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.12 GiB (GPU 2; 39.39 GiB total capacity; 5.38 GiB already allocated; 64.62 MiB free; 6.11 GiB reserved in total by PyTorch)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.39 GiB (GPU 3; 39.39 GiB total capacity; 4.74 GiB already allocated; 952.62 MiB free; 5.13 GiB reserved in total by PyTorch) 


I checked several examples on documentation, and it seems that my code has no problem for creating data loader and building model in a multi-process fashion.

**Comment by Algolzw** [comment]
Hi, sorry I haven't used the `torch.distributed.run` before so I don't know how to deal with this issue. But which process do you meet this OOM problem (training or validation)? Can you try to use only 1 GPU to train the model?

**Comment by shengyenlin** [comment]
Hi, 

I'm really grateful for your response, the problem is solved. I think it's due to my hardware settings.

In addition, I met two urgent problems that would need your help again.

1. I was wondering if this model could only input ".img" data? Since I saw the default data type is img, but you use SwinIR dataset to train your model, which contains .bmp or .png.

2. I found the code always stuck during the validation phase, and I found that you set the batch size in validation dataset to 1 and deactivate multi-GPU training here. May I ask you the reason about this, or is it possible to activate multi GPU training here? Otherwise it takes an hour to validate my validation data (which contains only 68 images)

Thanks in advance.

**Comment by Algolzw** [comment]
1. If opencv can open ".img" file then it should be fine. You can add it to the `IMG_EXTENSIONS` in [data utils](https://github.com/Algolzw/image-restoration-sde/blob/94664978d948c7bc632db41045227e6c0f3ffa48/codes/data/util.py#L12C1-L12C15).
2. Our code can validate the data with only 1 GPU. I guess your images are too large and one possible solution is to validate fewer data (or cropped data). But then you need to run all test images separately when the training is done.
3. The setting in option.yml is very flexible. I updated the code to `batch_size=8` and `iteration=700,000` to adapt my local server's old GPU, but of course you can change it again!

**Comment by shengyenlin** [comment]
Hi, 

Thanks for your quick response,

Concerning 3, since I want like to reproduce your result, is the result on your paper trained by `batch_size=8` and `iteration=700,000` or `batch_size` = 16 and `iteration=500,000`

**Comment by Algolzw** [comment]
No problem. It should be batch size 16 and iterations 500,000.

**Comment by shengyenlin** [comment]
Hi Algolzw,

I would like to ask one more question about a parameter in the `config.yaml`

```
sde:
  max_sigma: 70  # 0.5
  T: 1000
  schedule: cosine # cosine # linear

degradation:
  sigma: 50
  noise_type: G # Gaussian noise: G
```

What is the meaning of `sde.max_sigma` parameter here, is it equal to the noise that you add inside the model ? but what does 0.5 mean?

In addition, the `degradation.sigma` means the noise added to the image during the validation stage right?

Sorry for urging you a little bit, but it's an urgent matter for me now, and would be grateful if you could provide your help here.

**Comment by Algolzw** [comment]
Yes `sigma` is the validation noise level and `max_sigma` means the maximum noise level in training(in other words, in training the noise level is random selected from 0 to 70)you can just ignore the 0.5.

**Comment by shengyenlin** [comment]
Hi thanks for your prompt reply,

Concerning the dataset, I was wondering how the 8294 images were picked during the training process. It seems the total number of images of dataset from SwinIR is 8594 not 8294. In addition, there are 900 images from DIV2K, rather than 800 images. So the total number of images should be 8694.

I would be extremely grateful if you could provide help on this matter.

**Comment by shengyenlin** [comment]
Hi 

Thanks for the information about BSD500 training dataset, but I still have a little problem concerning the number of each dataset and would like to ask you to help me confirm

DIV2K (Agustsson & Timofte, 2017) - 900
Flickr2K (Timofte et al., 2017) - 2650
BSD500 (Arbelaez et al., 2010) training set - 200
Waterloo Exploration - 4744
Total: 8494

Could you tell me that what did I miss for adding 200 extra images here?

**Comment by Algolzw** [comment]
For DIV2K we only use its 800 training images. And I will check the number of dataset later.

Thanks for your careful feedback.

**Comment by shengyenlin** [comment]
Hi, 

I have another question concerning the parameter of denoising ir-sde 

In options/train/ir-sde.yml, the sde.max_sigma is 70 and the sde.T is 1000.

However, in `options/test/ir-sde.yml`, the sde.max_sigma is 75 and the sde.T is 100.

I remember that the T means the step of diffusion process. If I use the original settings, the SSIM and PSNR are pretty low. If I make sde.T to 1000 in test yml, the result seems reasonable.

Therefore, I would like to ask if I should synchronize the settings here. i.e. in `options/test/ir-sde.yml`, the sde.max_sigma should be set to 70 and the sde.T to 1000.

Sorry for urging you a little bit, but it's an urgent matter for me now, and would be grateful if you could provide your help here.

**Comment by Algolzw** [comment]
Yes you should keep the settings the same as the training. I forgot to update the test yml file for denoising, and I will update it later!

**Comment by shengyenlin** [comment]
Hi,

Thanks for your prompt response,

I would also like to ask you about the validation time of this de-noising model. For now, I use

```
sde:
  max_sigma: 70 
  T: 1000 

degradation:
  sigma: 50
  noise_type: G # Gaussian noise: G

```

and it takes over an hour to have the PSNR and SSIM value of my val set (BSD 68), is it normal due to the natural of the reverse process of diffusion models? Since we need to reverse the process step by step

**Comment by Algolzw** [comment]
Sure. But it would be faster (with less steps) when the sigma is small.

**Comment by shengyenlin** [comment]
I get it,

Also, would `max_sigma` and `T` affect the time of validation or inference here?

**Comment by Algolzw** [comment]
Yes, they should be the same as the training settings.

**Comment by shengyenlin** [comment]
Hi,

I would like to ask is it possible for to use this model to do "real image denoising"?

If so, how could I achieve it? And what your recommended setting to do this in terms of the following parameters:
```
sde:
  max_sigma: 70 
  T: 1000 

degradation:
  sigma: 50
  noise_type: G # Gaussian noise: G
```

**Comment by Algolzw** [comment]
Hi, the current denoising-sde can not be used for real noise. But you can easily train an original IR-SDE model by changing the dataset.

**Comment by shengyenlin** [comment]
Hi, 
Thanks for your prompt response,

By an original "IR-SDE" model, you mean using the "denoising-sde" directory in the repo?

**Comment by Algolzw** [comment]
You can refer to the [Deraining task](https://github.com/Algolzw/image-restoration-sde/tree/main/codes/config/deraining) and change the dataset settings.

**Comment by shengyenlin** [comment]
Hello, 
Thanks for your advice, I think I misunderstood the paper at the beginning and I'm really grateful for your clarification.

I have two questions when using the `deraining model` here.

1.  I found that in the train config of deraining model, the `max_sigma` is 10 and the `T` is 100. However, they are 70 and 1000 respectively in denoising-ODE. How could I choose hyper param here, is there any rule of thumb? If I want to use derain model for real-nose image denoising.

2. In the context of deraining, what's the meaning of `max_sigma` here, I think it's not the upper bound of random noise level (like what you said for de-noising ODE). In addition, which mathematical sign corresponds to `max_sigma` in option.yml in the paper. I couldn't really find it.

Thanks in advance.

**Comment by Algolzw** [comment]
I recommend the `max_sigma=10` and `T=1000` for real-noise datasets.  For other tasks, max_sigma means the noise level added to the low-quality images, and our IR-SDE will learn both denoising and deraining in the reverse-time process.

In our paper, the max_sigma is represented by the $\lambda$.

**Comment by shengyenlin** [comment]
Hi thanks for your reponse, I know how to deal with my real noise images.

I'm sorry to bother you again, but it's also a little bit urgent for me.

Since I want to compare this model to other models (like CNN, Restormer, GAN etc), I pre-added gaussian noise (noise level = 50) to my training set. Therefore, I have a HQ-LQ gaussian noise dataset.

I would like to ask how could I train the denoising-ODE model here, how could I just the code to solve my problem.

In addition, I'm a little bit confused about the code of denoising. In the `train.py`, we instantiated a denoisingSDE model, but is this a denoising-SDE or desnoising-ODE model? If it's the previous case, how could I find the denoising-ODE model. Also, I saw this model is still using the `max_sigma` (lambda) terms for training, but after I read the paper again this morning, in denoising-ODE, we don't have this term since we ignore the weiner process here

Thanks in advance.

**Comment by Algolzw** [comment]
Hi, if you want to training the model on the HQ-LQ paired dataset, you can simply modify the `dataset path` in the [deraining](https://github.com/Algolzw/image-restoration-sde/tree/main/codes/config/deraining) task's `training.yml` file. But if your dataset only has Gaussian noise, you can directly train the [denoising-ode](https://github.com/Algolzw/image-restoration-sde/tree/main/codes/config/denoising-sde) or use our pretrained weights.

In train.py the default model is denoising-ode, if you want to change it to denoising-sde you just need to change the `sde.reverse_sde` to `sde.reverse_ode` in the [test function](https://github.com/Algolzw/image-restoration-sde/blob/94664978d948c7bc632db41045227e6c0f3ffa48/codes/config/denoising-sde/models/denoising_model.py#L167C28-L167C28). Moreover, in denoising case the `max_sigma` is the noise_level's range from 0 to `max_sigma`, and we can restore any noise_level within this range.

For other noise types, I would like to recommend the IR-SDE.

Best.
