### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AIisCool** [Algolzw/image-restoration-sde#33]
```
/c/image-restoration-sde-main/codes/config/denoising-sde
$ python test.py -opt=options/test/ir-sde.yml
export CUDA_VISIBLE_DEVICES=0
Traceback (most recent call last):
  File "C:\image-restoration-sde-main\codes\config\denoising-sde\test.py", line 25, in <module>
    opt = option.parse(parser.parse_args().opt, is_train=False)
  File "C:\image-restoration-sde-main\codes\config\denoising-sde\options.py", line 60, in parse
    config_dir = path.split("/")[-2]
IndexError: list index out of range
```
How can I fix this? Thanks

**Comment by Algolzw** [comment]
Hi, if you use Windows you may need to replace the `"/"` with `"\"` in the options.py, line 60: https://github.com/Algolzw/image-restoration-sde/blob/94664978d948c7bc632db41045227e6c0f3ffa48/codes/config/denoising-sde/options.py#L60

**Comment by AIisCool** [comment]
I tried changing it but:

```
/c/image-restoration-sde-main/codes/config/denoising-sde
$ python test.py -opt=options/test/ir-sde.yml
Traceback (most recent call last):
  File "C:\image-restoration-sde-main\codes\config\denoising-sde\test.py", line 14, in <module>
    import options as option
  File "C:\image-restoration-sde-main\codes\config\denoising-sde\options.py", line 60
    config_dir = path.split("\")[-2]
                            ^
SyntaxError: unterminated string literal (detected at line 60)

```

**Comment by Algolzw** [comment]
Can you print the `path` and find the correct split symbol?

**Comment by AIisCool** [comment]
Not sure how to do that?

**Comment by Algolzw** [comment]
Hi you can just add one line `print(path)` to the options.py file before line 60.
