### ISSUE TITLE
unet-latent训练时bug汇报

### ISSUE THREAD

**Issue by yousaLING** [Algolzw/image-restoration-sde#74]
bug:如果重新对unet进行训练的时候，没有在unet-latent下创建image文件夹训练到5000iter test的时候会报错，创建后就正常，建议在调用train.py初始化的时候增加对是否有image文件夹的验证并自动创建。
    顺便问一下大佬，因为你们提供的是对 NTIRE 数据集的预训练模型，如果我要对RESIDE数据集512*512规格大小进行重新训练的话，unet和latent-dehazing使用的数据集都是一模一样的13990张图片吗？就**size大小**不一样吗，unet GT_size和LR_size 256，然后latent-dehazing GT_size和LR_size变成512吗，还是说unet的size也要修改成512？
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    main()
  File "train.py", line 264, in main
    model.test()
  File "/hy-tmp/refusion/codes/config/unet-latent/models/latent_model.py", line 194, in test
    tvutils.save_image(self.LQ.data, f'image/LQ.png', normalize=False)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torchvision/utils.py", line 151, in save_image
    im.save(fp, format=format)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 2350, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'image/LQ.png'
![1706781393542](https://github.com/Algolzw/image-restoration-sde/assets/60027314/e33af60d-2537-41c3-ab39-d96c62a7a1d2)

**Comment by Algolzw** [comment]
感谢告知！之后我会对此进行更新。

我个人经验是训练U-Net的话size影响好像不太大，但训练latent-sde的话size越大越好。
