### ISSUE TITLE
AssertionError: datasets/rain/trainH/LQ is not a valid directory

### ISSUE THREAD

**Issue by FengEternity** [Algolzw/image-restoration-sde#9]
I set up the dataset according to the operation you provided, but the following error still occurred at runtime, do you know why, thank you

Traceback (most recent call last):
  File "train.py", line 319, in <module>
    main()
  File "train.py", line 156, in main
    train_set = create_dataset(dataset_opt)
  File "/LF/image-restoration-sde/codes/config/deraining/../../data/__init__.py", line 45, in create_dataset
    dataset = D(dataset_opt)
  File "/LF/image-restoration-sde/codes/config/deraining/../../data/LQGT_dataset.py", line 40, in __init__
    self.LR_paths = util.get_image_paths(
  File "/LF/image-restoration-sde/codes/config/deraining/../../data/util.py", line 48, in get_image_paths
    paths = sorted(_get_paths_from_images(dataroot))
  File "/LF/image-restoration-sde/codes/config/deraining/../../data/util.py", line 19, in _get_paths_from_images
    assert os.path.isdir(path), '{:s} is not a valid directory'.format(path)
AssertionError: datasets/rain/trainH/LQ is not a valid directory

**Comment by Algolzw** [comment]
It seems the system can't find the 'datasets/rain/trainH/LQ' directory. You can check whether the directory exists.
